eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://node02:7902/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 10090
spring:
  application:
    name: ServiceClient
  boot:
    admin:
      client:
        url: 'http://localhost:8081'
  zipkin:
    base-url: 'http://localhost:9411/'
  sleuth:
    sampler:
      rate: 1        

custom:
  testProperty: TestPropertyValue-3
