eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://node02:7902/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 10090
spring:
  application:
    name: ServiceClient
    test-property: TestPropertyValue
  boot:
    admin:
      client:
        url: 'http://localhost:8081'
